name: transito
description: Get on board with Transito and catch your bus right on time!

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 4.1.0+42

environment:
    sdk: ">=3.1.0 <4.0.0"

scripts:
    dev: firebase emulators:start; flutter run

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter

    cupertino_icons: ^1.0.2
    jiffy: ^6.2.1
    latlong2: ^0.9.0
    geolocator: ^14.0.0
    provider: ^6.0.3
    json_annotation: ^4.8.1
    http: ^1.1.0
    alphanum_comparator: ^2.0.1
    photo_view: ^0.15.0
    flutter_svg: ^2.0.7
    parent_child_checkbox:
        git:
            url: https://github.com/TechSupportz/parent-child-checkbox
    is_first_run: ^1.0.0
    flutter_form_builder: ^10.0.1
    form_builder_validators: ^11.0.0
    android_intent_plus: ^5.1.0
    url_launcher: ^6.1.5
    firebase_core: ^3.8.1
    firebase_auth: ^5.3.4
    cloud_firestore: ^5.5.1
    google_sign_in: ^6.1.0
    sign_in_with_apple: ^7.0.1
    flutter_map: ^8.2.0
    flutter_native_splash: ^2.4.6
    package_info_plus: ^8.0.2
    upgrader: ^11.3.0
    shared_preferences: ^2.2.2
    posthog_flutter: ^5.0.0
    measure_size: ^4.0.0
    flutter_skeleton_ui: ^0.0.6
    collection: ^1.18.0
    smooth_highlight: ^0.1.1
    flutter_colorpicker: ^1.1.0
    animations: ^2.0.11
    google_polyline_algorithm: ^3.1.0
    flutter_map_animations: ^0.9.0
    flutter_map_location_marker: ^10.1.0
    flutter_map_marker_cluster:
        git:
            url: "https://github.com/matteomrz/flutter_map_marker_cluster"
    material_symbols_icons: ^4.2858.1

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^5.0.0
    json_serializable: ^6.7.1
    build_runner: ^2.1.11

flutter_native_splash:
    ios: true
    color: "#F1EDFD"
    color_dark: "#030108"
    android: true
    image: "assets/icons/a12-splash-1152x1152.png"
    android_12:
        image: "assets/icons/a12-splash-1152x1152.png"
        color: "#F1EDFD"
        icon_background_color: "#F1EDFD"
        color_dark: "#030108"
        icon_background_color_dark: "#030108"

flutter:
    uses-material-design: true

    assets:
        - assets/
        - assets/images/
        - assets/icons/
        - assets/icons/ui/
        - shorebird.yaml

    fonts:
        - family: Poppins
          fonts:
              - asset: assets/fonts/Poppins-Regular.ttf
              - asset: assets/fonts/Poppins-Italic.ttf
                style: italic
              - asset: assets/fonts/Poppins-Medium.ttf
                weight: 500
              - asset: assets/fonts/Poppins-MediumItalic.ttf
                weight: 500
                style: italic
              - asset: assets/fonts/Poppins-SemiBold.ttf
                weight: 600
              - asset: assets/fonts/Poppins-Bold.ttf
                weight: 700

        - family: Itim
          fonts:
              - asset: assets/fonts/Itim-Regular.ttf
