name: transito
description: Get on board with Transito and catch your bus right on time!

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.2.0+24

environment:
    sdk: ">=3.1.0 <4.0.0"

scripts:
    dev: firebase emulators:start; flutter run

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter

    cupertino_icons: ^1.0.2
    jiffy: ^6.2.1
    latlong2: ^0.9.0
    geolocator: ^13.0.1
    provider: ^6.0.3
    json_annotation: ^4.8.1
    http: ^1.1.0
    alphanum_comparator: ^2.0.1
    photo_view: ^0.15.0
    flutter_svg: ^2.0.7
    parent_child_checkbox:
        git:
            url: https://github.com/TechSupportz/parent-child-checkbox
    is_first_run: ^1.0.0
    flutter_form_builder: ^9.1.0
    form_builder_validators: ^11.0.0
    android_intent_plus: ^5.1.0
    url_launcher: ^6.1.5
    firebase_core: ^2.13.0
    firebase_auth: ^4.6.1
    cloud_firestore: ^4.7.1
    google_sign_in: ^6.1.0
    sign_in_with_apple: ^6.1.1
    flutter_map: ^7.0.2
    form_builder_extra_fields: ^10.0.0
    flutter_native_splash: ^2.1.2+1
    package_info_plus: ^8.0.2
    upgrader: ^10.3.0
    shared_preferences: ^2.2.2
    posthog_flutter: ^4.5.0
    measure_size: ^4.0.0
    flutter_skeleton_ui: ^0.0.6

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^4.0.0
    json_serializable: ^6.7.1
    build_runner: ^2.1.11

flutter_native_splash:
    color: "#000000"
    android: true
    ios: true
    image: "assets/images/logo.png"
    android_12:
        image: "assets/icons/a12-splash-1152x1152.png"
        icon_background_color: "#030108"
        color: "#000000"

flutter:
    uses-material-design: true

    assets:
        - assets/
        - assets/images/
        - assets/icons/
        - shorebird.yaml

    fonts:
        - family: Poppins
          fonts:
              - asset: assets/fonts/Poppins-Regular.ttf
              - asset: assets/fonts/Poppins-Italic.ttf
                style: italic
              - asset: assets/fonts/Poppins-Medium.ttf
                weight: 500
              - asset: assets/fonts/Poppins-MediumItalic.ttf
                weight: 500
                style: italic
              - asset: assets/fonts/Poppins-SemiBold.ttf
                weight: 600
              - asset: assets/fonts/Poppins-Bold.ttf
                weight: 700

        - family: Itim
          fonts:
              - asset: assets/fonts/Itim-Regular.ttf
