name: transito
description: A bus timing application to view your bus arrival timings in Singapore swiftly.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0+8

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  jiffy: ^5.0.0
  latlong2: ^0.8.1
  geolocator: ^8.2.1
  provider: ^6.0.3
  json_annotation: ^4.5.0
  http: ^0.13.4
  alphanum_comparator: ^2.0.1
  photo_view: ^0.14.0
  flutter_svg: ^1.0.3
  parent_child_checkbox:
    git:
      url: https://github.com/TechSupportz/parent-child-checkbox
  is_first_run: ^1.0.0
  firebase_core: ^1.20.0
  firebase_auth: ^3.4.1
  flutter_form_builder: 7.1.1
  form_builder_validators: ^8.1.1
  android_intent_plus: ^3.1.1
  url_launcher: ^6.1.5
  google_sign_in: ^5.4.0
  cloud_firestore: ^3.4.1
  flutter_map: ^2.2.0
  form_builder_extra_fields: ^7.1.0
  flutter_native_splash: ^2.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  json_serializable: ^6.2.0
  build_runner: ^2.1.11
  flutter_launcher_icons: "^0.9.2"


flutter_native_splash:
  color: "#000000"
  android: true
  ios: true
  image: "assets/images/logo.png"
  android_12:
    image: "assets/icons/a12-splash-1152x1152.png"
    icon_background_color: "#0c0c0c"
    color: "#000000"


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/Icon-1024x1024.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icons/icon-foreground-1024x1024.png"
  adaptive_icon_padding: true


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

    - family: Itim
      fonts:
        - asset: assets/fonts/Itim-Regular.ttf


